"""What the seeded backups must do. The runtime does not read this file."""

EXPECTED = {
    "DED-1001": {
        "reason": "shortage",
        "outcome": "valid",
        "queue": "warehouse",
        "organization": "logistics",
        "citation": "MSA-2024-118 §4.2",
        "phrase": "15 days",
    },
    "DED-1002": {
        "reason": "shortage",
        "outcome": "invalid",
        "queue": "recovery",
        "organization": "recovery",
        "citation": "MSA-2025-077 §4.2",
        "phrase": "10 days",
    },
    "DED-1003": {
        "reason": "pricing",
        "outcome": "valid",
        "queue": "sales",
        "organization": "sales",
        "citation": "PROMO-2026-Q1 §1",
        "phrase": "$1.25",
    },
    "DED-1004": {
        "reason": "pricing",
        "outcome": "invalid",
        "queue": "recovery",
        "organization": "recovery",
        "citation": "MSA-2025-077 §5.1",
        "phrase": "written promotion",
    },
    "DED-1005": {
        "reason": "returns",
        "outcome": "valid",
        "queue": "returns",
        "organization": "customer_operations",
        "citation": "MSA-2024-118 §6.3",
        "phrase": "60 days",
    },
    "DED-1006": {
        "reason": "returns",
        "outcome": "invalid",
        "queue": "recovery",
        "organization": "recovery",
        "citation": "MSA-2025-077 §6.3",
        "phrase": "no RMA",
    },
    "DED-1007": {
        "reason": "coop_advertising",
        "outcome": "valid",
        "queue": "sales_coop",
        "organization": "sales",
        "citation": "COOP-2025-NL §2",
        "phrase": "45 days",
    },
    "DED-1008": {
        "reason": "coop_advertising",
        "outcome": "invalid",
        "queue": "recovery",
        "organization": "recovery",
        "citation": "MSA-2025-077 §8.1",
        "phrase": "separate written agreement",
    },
    "DED-1009": {
        "reason": "damaged_goods",
        "outcome": "valid",
        "queue": "quality",
        "organization": "quality",
        "citation": "MSA-2024-118 §7.4",
        "phrase": "10 days",
    },
    "DED-1010": {
        "reason": "damaged_goods",
        "outcome": "invalid",
        "queue": "recovery",
        "organization": "recovery",
        "citation": "MSA-2024-118 §7.4",
        "phrase": "10 days",
    },
}
